### ISSUE TITLE
Add TravisCI or CircleCI config

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/babel-merge#10]
Since currently the tests in this repo are not run on push.

**Comment by eliperelman** [comment]
I was literally coming to write this issue 😆

**Comment by ndelangen** [comment]
I'd suggest adding CircleCI, we use it and it's amazing:
https://circleci.com/gh/storybooks/workflows

**Comment by eliperelman** [comment]
I'm probably going to add Travis for now, and then we can evaluate moving all 3 of our major repos to Circle at the same time.
