### ISSUE TITLE
Enable Renovate on this repo

### ISSUE THREAD

**Issue by edmorley** [neutrinojs/babel-merge#5]
Now that babel-merge has more substantial dependencies (babel), we should enable Renovate to keep them up to date.

This is particularly important when Babel is still in beta/RC, since both `babel-merge` and `@neutrinojs/compile-loader` are now pinning to exact babel versions, and at the moment have different versions referenced, meaning two copies of Babel are downloaded/installed/used together.

**Comment by eliperelman** [comment]
Fixed by #6.
